/**
 * Default topic queue — the Tier 1 / Tier 2 rows from
 * docs/seo-keyword-targets.md, framed for the blog: every entry is a
 * SUPPORTING post that links to the money page in `target_url` and must not
 * take that page's commercial keyword as its own primary keyword.
 *
 * Applied from the admin ("Seed defaults"), never from SQL, so slugs resolve
 * to ids at runtime and the rows can be reviewed before the agent sees them.
 */
import type { TopicData } from "./schemas";

const LA = "los-angeles-county";

export const SEED_TOPICS: TopicData[] = [
  // Tier 1
  {
    keyword: "neck injury lawyer",
    intent: "informational",
    practice_area_slug: "car-accidents",
    target_url: "/practice-areas/car-accidents",
    priority: 10,
    volume: 1600,
    kd: 10,
    cpc: 122,
    notes: "Symptom intent. Explain whiplash/neck-injury claims, documentation, and when to call a lawyer.",
    source: "seed",
  },
  {
    keyword: "los angeles truck accident lawyer",
    intent: "supporting_post",
    practice_area_slug: "truck-accidents",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/truck-accidents`,
    priority: 12,
    volume: 2900,
    kd: 19,
    cpc: 157,
    notes: "Angle: what makes LA truck crash claims different (federal motor-carrier rules, evidence preservation).",
    source: "seed",
  },
  {
    keyword: "lyft accident lawyers",
    intent: "supporting_post",
    practice_area_slug: "rideshare-accidents",
    county_slug: LA,
    city_slug: "glendale",
    target_url: `/locations/${LA}/glendale/rideshare-accidents`,
    priority: 14,
    volume: 2400,
    kd: 17,
    cpc: 154,
    notes: "Name Uber AND Lyft explicitly. Angle: the three insurance periods by app status.",
    source: "seed",
  },
  {
    keyword: "lawyer for uber accident",
    intent: "supporting_post",
    practice_area_slug: "rideshare-accidents",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/rideshare-accidents`,
    priority: 16,
    volume: 1300,
    kd: 22,
    cpc: 173,
    notes: "Passenger vs. other-driver vs. driver claims against Uber coverage.",
    source: "seed",
  },
  {
    keyword: "los angeles motorcycle accident lawyer",
    intent: "supporting_post",
    practice_area_slug: "motorcycle-accidents",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/motorcycle-accidents`,
    priority: 18,
    volume: 2400,
    kd: 21,
    cpc: 120,
    notes: "Angle: rider bias and how liability is proven; lane-splitting rules.",
    source: "seed",
  },
  {
    keyword: "wrongful death attorney los angeles",
    intent: "supporting_post",
    practice_area_slug: "wrongful-death",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/wrongful-death`,
    priority: 20,
    volume: 1600,
    kd: 19,
    cpc: 102,
    notes: "Sensitive tone. Who may bring a claim in California, damages categories, deadlines.",
    source: "seed",
  },
  {
    keyword: "los angeles car accident attorney",
    intent: "supporting_post",
    practice_area_slug: "car-accidents",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/car-accidents`,
    priority: 22,
    volume: 3600,
    kd: 26,
    cpc: 156,
    notes: "Angle: first 72 hours after an LA crash; LAPD vs CHP reports.",
    source: "seed",
  },
  {
    keyword: "glendale car accident lawyer",
    intent: "supporting_post",
    practice_area_slug: "car-accidents",
    county_slug: LA,
    city_slug: "glendale",
    target_url: `/locations/${LA}/glendale/car-accidents`,
    priority: 24,
    volume: 720,
    kd: 15,
    cpc: 116,
    notes: "Local angle: Brand Blvd / 134 / 2 interchanges; Glendale PD reports.",
    source: "seed",
  },
  {
    keyword: "personal injury lawyer glendale",
    intent: "informational",
    practice_area_slug: "car-accidents",
    county_slug: LA,
    city_slug: "glendale",
    target_url: `/locations/${LA}/glendale`,
    priority: 26,
    volume: 720,
    kd: 13,
    cpc: 44,
    notes: "Angle: how to choose a personal-injury lawyer in Glendale; questions to ask.",
    source: "seed",
  },
  // Tier 2
  {
    keyword: "los angeles bicycle accident lawyer",
    intent: "supporting_post",
    practice_area_slug: "bicycle-accidents",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/bicycle-accidents`,
    priority: 30,
    volume: 1300,
    kd: 34,
    cpc: 240,
    notes: "Door-zone, hit-from-behind, bike-lane rules in LA.",
    source: "seed",
  },
  {
    keyword: "catastrophic injury attorney los angeles",
    intent: "supporting_post",
    practice_area_slug: "catastrophic-injury",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: "/practice-areas/catastrophic-injury",
    priority: 32,
    volume: 1300,
    kd: 27,
    notes: "Life-care planning, future costs, expert proof.",
    source: "seed",
  },
  {
    keyword: "slip and fall lawyer los angeles",
    intent: "supporting_post",
    practice_area_slug: "slip-and-fall",
    county_slug: LA,
    city_slug: "los-angeles",
    target_url: `/locations/${LA}/los-angeles/slip-and-fall`,
    priority: 34,
    volume: 1000,
    kd: 25,
    cpc: 203,
    notes: "Notice, incident reports, surveillance footage preservation.",
    source: "seed",
  },
];
